// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ScaleSync Pro Firebase Configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgE2e8RPN0JOWR8MFA1HTfDos3qmmkmEg',
    appId: '1:123833527982:web:36b21425fc1127c290473f',
    messagingSenderId: '123833527982',
    projectId: 'scalesync-pro',
    authDomain: 'scalesync-pro.firebaseapp.com',
    storageBucket: 'scalesync-pro.firebasestorage.app',
    measurementId: 'G-9BCWD33SRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgE2e8RPN0JOWR8MFA1HTfDos3qmmkmEg',
    appId: '1:123833527982:android:36b21425fc1127c290473f',
    messagingSenderId: '123833527982',
    projectId: 'scalesync-pro',
    authDomain: 'scalesync-pro.firebaseapp.com',
    storageBucket: 'scalesync-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgE2e8RPN0JOWR8MFA1HTfDos3qmmkmEg',
    appId: '1:123833527982:ios:36b21425fc1127c290473f',
    messagingSenderId: '123833527982',
    projectId: 'scalesync-pro',
    authDomain: 'scalesync-pro.firebaseapp.com',
    storageBucket: 'scalesync-pro.firebasestorage.app',
    iosBundleId: 'com.scalesyncpro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgE2e8RPN0JOWR8MFA1HTfDos3qmmkmEg',
    appId: '1:123833527982:macos:36b21425fc1127c290473f',
    messagingSenderId: '123833527982',
    projectId: 'scalesync-pro',
    authDomain: 'scalesync-pro.firebaseapp.com',
    storageBucket: 'scalesync-pro.firebasestorage.app',
    iosBundleId: 'com.scalesyncpro.app',
  );
} 